# Docs: https://git.io/JCUAY
version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "monthly"
    reviewers:
      - "@sourcegraph/core-services"
    commit-message:
      prefix: "mod:"
